title: 'Hello PowerShell World '
tagline: A brand new course on Learning Lab
description: 'Welcome to the PowerShell World '
template:
  repo: hello-powershell-world-template
  name: hello-powershell-world
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
